### ISSUE TITLE
UI/ UX - Make the changes to the signup / login page , allowing user to know all the constraints 

### ISSUE THREAD

**Issue by ROHITHDHARURU** [ROHITHDHARURU/project680#10]
As mentioned by the professor, user has to know the password constraints in terms of text . ex : (<a-Z>,<0-9>,&,*)
Also evaluate this for the other fields and  update the estimated time to fix the issues.

**Comment by NavyaSreeG99** [comment]
![signup-error](https://github.com/ROHITHDHARURU/project680/assets/112337390/5892e4d6-52cb-4e4c-bb9f-289d58b84d93)

1. After giving credentials and **sign-up** button is clicked there is no action being shown. 
2. Password Constriants were not shown like : 
- Minimum Length(8 character length)
- Uppercase Letters: Include at least one uppercase letter.
- Lowercase Letters: Include at least one lowercase letter.
- Numbers: Include at least one digit (0-9).
- Special Characters: Encourage the use of special characters (e.g., !, @, #, $, %).
3. No action is shown when clicked on **save data** after giving some expression and generated the truth table.
4. Sign up page Place holder is given to only email which looks odd.

**Comment by NavyaSreeG99** [comment]
1. Better to keep a title above truth table: " Truth table for Active Clause Coverage..."
2. When save Data button is clicked, no message is displayed if it is saved or not saved or which truth table is saved etc.
3. for the history " generate truth table" is being shown on the main column changing the truth table... " so it is better to either maintain a title or " for the history table , let it be below the "generate truth table button there itself"
4. when the same expression and same coverage is already existing in the history. how would it be if it displays "expression coverage is already existing in history".

**Comment by ROHITHDHARURU** [comment]
@NavyaSreeG99 . Most of the issues are addressed in the recent commit, please get the latest build and test.
Note: We could not implement new issues, considering the timeline and priority.

, In our application user will only login when his use cases are complex, and user must know the expression. We provide history to the user, as some of the expressions might be complex and hard to remember. Its up to the user if they want to save all the expressions. I don't think so we need to truncate the duplicate expressions, as our idea of implementing history is to pertain user work. 

Please test and close the issue.
=

**Comment by ROHITHDHARURU** [comment]
fixed and hence closing the issue
